name: segmentation
dependencies:
    - h5py=2.7
    - jupyter=1.0
    - matplotlib=2.2
    - numpy=1.14
    - pytorch
    - torchvision
    - cuda91
    - scikit-image=0.13
    - scikit-learn=0.19
channels:
    - pytorch
